# Smart pane switching with awareness of Vim splits
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

# Use Alt-vim keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n M-1 switch-client -t 1
bind -n M-2 switch-client -t 2
bind -n M-3 switch-client -t 3
bind -n M-4 switch-client -t 4
bind -n M-5 switch-client -t 5
bind -n M-6 switch-client -t 6
bind -n M-7 switch-client -t 7

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# bind-key C-d detach-client
bind-key C-d detach-client

# Use v and s for windows splits
bind-key v split-window -h
bind-key s split-window -v

# Use m to toggle mouse mode
unbind m
bind m setw mouse

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# Intuitive split commands
bind | split-window -h
bind - split-window -v

# Open splits in the same directory
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Set Escape time to 10 ms
set -sg escape-time 10
